### ISSUE TITLE
getting --> TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by sumit2061902** [newrelic/newrelic-salesforce-exporter#53]
[NOTE]: # ( ^^ TypeError: 'str' object does not support item assignment ^^ )

## Description

python3.9 ./src/__main__.py config.yml
2024-09-17 12:09:51,238 (9442/MainThread) newrelic.core.agent INFO - New Relic Python Agent (9.7.0)
{"message": "Integration start. Using program arguments ['config.yml']", "timestamp": 1726539001254, "level": "info"}
Traceback (most recent call last):
  File "/home/tcadmin/newrelic-salesforce-exporter/./src/__main__.py", line 278, in <module>
    main()
  File "/home/tcadmin/.local/lib/python3.9/site-packages/newrelic/api/background_task.py", line 111, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/tcadmin/newrelic-salesforce-exporter/./src/__main__.py", line 272, in main
    run(config, event_type_fields_mapping, numeric_fields_list)
  File "/home/tcadmin/newrelic-salesforce-exporter/./src/__main__.py", line 213, in run
    run_once(
  File "/home/tcadmin/newrelic-salesforce-exporter/./src/__main__.py", line 160, in run_once
    factory.new_integration(
  File "/home/tcadmin/newrelic-salesforce-exporter/src/newrelic_logging/factory.py", line 168, in new_integration
    labels['nr-labs'] = 'data'
**TypeError: 'str' object does not support item assignment**
2024-09-17 12:10:01,327 (9442/MainThread) newrelic.core.agent INFO - New Relic Python Agent Shutdown

## Steps to Reproduce
running this command after cloning the repository and making the changes in config..yml -->python3.9 ./src/__main__.py config.yml

## Expected Behavior
it should integrate with salesforce and newrelic

## Your Environment
Linux

**Comment by sdewitt-newrelic** [comment]
Hi @shankarlaksh , could you please update to the latest version of the integration and retry?  Also could you share your configuration (please be sure to redact all keys before posting)?
